"""Validate all binary data files generated by mkconfig using the datadump tool."""

import pathlib
import shutil
import subprocess
import tempfile

import pytest

DOMINION_DIR = pathlib.Path(__file__).resolve().parent.parent


@pytest.fixture(scope="module")
def data_workdir(mkconfig_binary):
    """Create a temp workdir with all data files (mkconfig + dist copies).

    Lighter than bbs_instance — no BBS process, just the data files.
    """
    workdir = pathlib.Path(tempfile.mkdtemp(prefix="dom_dd_", dir="/tmp"))

    # Run mkconfig to generate binary data files
    result = subprocess.run(
        [str(mkconfig_binary), str(workdir) + "/"],
        capture_output=True,
        timeout=10,
    )
    if result.returncode != 0:
        pytest.fail(
            f"mkconfig failed:\n"
            f"{result.stdout.decode('latin-1', errors='replace')}\n"
            f"{result.stderr.decode('latin-1', errors='replace')}"
        )

    # Copy menus from dist/ (mkconfig doesn't generate these)
    src_menus = DOMINION_DIR / "dist" / "menus"
    dst_menus = workdir / "menus"
    if src_menus.is_dir():
        if dst_menus.exists():
            shutil.rmtree(dst_menus)
        shutil.copytree(str(src_menus), str(dst_menus))

    yield workdir

    shutil.rmtree(str(workdir), ignore_errors=True)


class TestDataValidation:
    """Validate all binary data files generated by mkconfig."""

    def test_config_dat(self, data_workdir, datadump_binary):
        """Config.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "config.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_status_dat(self, data_workdir, datadump_binary):
        """data/status.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "status.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_user_lst(self, data_workdir, datadump_binary):
        """data/user.lst passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "user.lst")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_user_idx(self, data_workdir, datadump_binary):
        """data/user.idx passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "user.idx")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_subs_dat(self, data_workdir, datadump_binary):
        """data/subs.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "subs.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_dirs_dat(self, data_workdir, datadump_binary):
        """data/dirs.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "dirs.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_protocol_dat(self, data_workdir, datadump_binary):
        """data/protocol.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "protocol.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_conf_dat(self, data_workdir, datadump_binary):
        """data/conf.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "conf.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_archive_dat(self, data_workdir, datadump_binary):
        """data/archive.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "archive.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_results_dat(self, data_workdir, datadump_binary):
        """data/results.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "results.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_acs_dat(self, data_workdir, datadump_binary):
        """data/acs.dat passes validation."""
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(data_workdir / "data" / "acs.dat")],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_dist_results_dat(self, datadump_binary):
        """dist/data/results.dat passes validation (may have trailing bytes from DOS era)."""
        dist_results = DOMINION_DIR / "dist" / "data" / "results.dat"
        if not dist_results.exists():
            pytest.skip("dist/data/results.dat not found")
        result = subprocess.run(
            [str(datadump_binary), "--validate", str(dist_results)],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")

    def test_truncated_file_fails(self, data_workdir, datadump_binary):
        """A truncated file should produce validation errors (exit 1)."""
        bad = data_workdir / "data" / "bad_status.dat"
        bad.write_bytes(b"\x00" * 10)  # way too short for statusrec
        result = subprocess.run(
            [str(datadump_binary), "--validate", "--type", "status", str(bad)],
            capture_output=True,
            timeout=10,
        )
        assert result.returncode == 1, "Expected exit 1 for truncated file"

    def test_dump_mode_prints_output(self, data_workdir, datadump_binary):
        """Normal mode (no --validate) should print human-readable output."""
        result = subprocess.run(
            [str(datadump_binary), str(data_workdir / "config.dat")],
            capture_output=True,
            timeout=10,
        )
        stdout = result.stdout.decode("latin-1", errors="replace")
        assert result.returncode == 0, result.stderr.decode("latin-1", errors="replace")
        assert "configrec" in stdout
        assert "Validation: OK" in stdout

    def test_sizes_flag(self, datadump_binary):
        """--sizes prints struct sizes and exits 0."""
        result = subprocess.run(
            [str(datadump_binary), "--sizes"],
            capture_output=True,
            timeout=10,
        )
        stdout = result.stdout.decode("latin-1", errors="replace")
        assert result.returncode == 0
        assert "configrec" in stdout
        assert "userrec" in stdout
